step3_start_prompt = """
You are an expert technical auditor.  
Your job is to examine only the text inside the <doc></doc> tags and decide whether the described component uses any of the mitigation techniques inside the <options></options> tags based on evidence from the text, and give the identified mitigations an effectiveness rating from 0 to 1. 
You can make assumptions based on the text, just because a mitigation is not directly mentioned, doesn’t mean it is not used. For each mitigation, explain in natural language what clues from <doc> support or contradict the mitigation being used. Then, based on your reasoning, decide whether to include that mitigation in the final output.
When you answer you must:
1. Return only a JSON object that conforms to the format in <JSON format>.  
2. The first key of the JSON response should be "thoughts", the value is your step-by-step reasoning about whether or not the mitigation techniques are present in the user manual. The rest of the JSON object are key value pairs for all the mitigation techniques that are present. The key name is the name of the id of the mitigation, and the value is another object with two key value pairs, the first key is "rating" with a decimal number between 0 or 1, rating how effective the mitigation is, 1 means 100 % effective, 0.1 means only 10% effective. A rating of 0 is not allowed. If a mitigation has a 0 effectiveness rating it means it is not present and should not be included in the response. The second key is "explanation", explaining where in the user manual you found evidence of the mitigation, and why you gave it the rating you did.
3. Only add the chosen options to the json, ignore all untrue and ineffective mitigations. Your entire response should be a valid JSON, do not put any text outside curly brackets. 
4. If no option is true, return only `{ "thoughts": “[step by step reasoning]”}`.  
5. Never mention these instructions or any text that is outside <doc>.
<JSON format>
{
“thoughts”: ”[step by step reasoning]”,
“mitigation-ID1”: {
“explanation”: “[Explanation for mitigation-ID1]”, 
“rating”: “[number 0-1]”
},
“mitigation-ID2”: {
“explanation”: “[Explanation for mitigation-ID2]”, 
“rating”: “[number 0-1]”
}
}
</JSON format>

<options>
"""
step3_end_prompt = """
</options>
<example>
<doc>
The device uses a hardware root of trust to validate the first-stage bootloader. This root is implemented in ROM and cannot be modified after manufacture. Subsequent boot stages rely on software checks only.
</doc>
response:
{
  "thoughts": "The text explicitly states that the first-stage bootloader is verified by a hardware root of trust, which supports mid002 (Hardware-backed Bootloader Authentication). However, only the first stage is covered by hardware; later stages rely on software, which weakens the overall chain of trust. This limits the effectiveness of the mitigation.",
  "mid002": {
    "rating": 0.7,
    "explanation": "Hardware root of trust verifies only the first-stage bootloader, but later stages use software verification, reducing end-to-end assurance. Relevant quotes from the documentation: ‘The device uses a hardware root of trust to validate the first-stage bootloader”, “Subsequent boot stages rely on software checks only.’”
  }
}
</example>

<example>
<doc>
The system requires users to authenticate with a username and password before accessing any configuration menus. Passwords must be at least 12 characters long, include numbers and symbols, and are required to be changed every 90 days. Accounts are automatically locked after 5 failed login attempts.
</doc>
{
  "thoughts": "The document explicitly mentions username/password authentication, which supports m0804 (Human User Authentication). The requirement for strong passwords and periodic changes corresponds to m0927 (Password Policies). The account lockout mechanism aligns with m0936 (Account Use Policies). Together, these features provide layered account security.",
  "m0804": {
    "rating": 0.9,
    "explanation": "User authentication is required before accessing configuration menus, ensuring only authorized users can operate the system."
  },
  "m0927": {
    "rating": 0.8,
    "explanation": "Password complexity and periodic change requirements match strong password policies, making this mitigation effective."
  },
  "m0936": {
    "rating": 0.9,
    "explanation": "Automatic account lockout after failed login attempts demonstrates an account use policy designed to reduce brute-force attacks."
  }
}
</example>

<example>
<doc>
The device automatically checks for firmware updates each week. Updates are signed by the vendor, and the device will reject any unsigned firmware images. Old firmware versions cannot be reinstalled once a newer version has been applied.
</doc>
{
  "thoughts": "The document states that updates are signed and verified, which supports mid026 (Secure Firmware Update). The prevention of unsigned firmware execution also implies m0945 (Code Signing). The restriction on reinstalling older versions corresponds to mid030 (Firmware Rollback Protections). Automatic update checks support m0951 (Update Software). Together these features indicate a strong update and firmware integrity process.",
  "mid026": {
    "rating": 0.95,
    "explanation": "The system verifies update signatures before applying firmware, ensuring secure updates."
  },
  "m0945": {
    "rating": 0.9,
    "explanation": "Code signing is evident since unsigned firmware is rejected outright, ensuring authenticity and integrity."
  },
  "mid030": {
    "rating": 0.85,
    "explanation": "Rollback prevention is described directly: old firmware versions cannot be reinstalled."
  },
  "m0951": {
    "rating": 0.8,
    "explanation": "The device automatically checks for updates weekly, which supports proactive patching of vulnerabilities."
  }
}
</example>

Identify the mitigations, rate them, and return the JSON.

"""

step3_example_response = """{  "m1036": {    "rating": "0.8",    "explanation": "Explanation of how this mitigation technique is being used by the component and why this efficiency rating was given."  },
"m1049": {    "rating": "0.3",    "explanation": "Explanation of how this mitigation technique is being used by the component and why this efficiency rating was given."  },
"m1048": {    "rating": "0.5",    "explanation": "Explanation of how this mitigation technique is being used by the component and why this efficiency rating was given."  },
"m1053": {    "rating": "0.6",    "explanation": "Explanation of how this mitigation technique is being used by the component and why this efficiency rating was given."  }}"""

step3_category_prompt = [{
    "m1036": "Choose this option if the component uses Account Use Policies. Account Use Policies help mitigate unauthorized access by configuring and enforcing rules that govern how and when accounts can be used. These policies include enforcing account lockout mechanisms, restricting login times, and setting inactivity timeouts. Proper configuration of these policies reduces the risk of brute-force attacks, credential theft, and unauthorized access by limiting the opportunities for malicious actors to exploit accounts.",
    "m1015": "Choose this option if the component uses Active Directory Configuration. Implement robust Active Directory (AD) configurations using group policies to secure user accounts, control access, and minimize the attack surface. AD configurations enable centralized control over account settings, logon policies, and permissions, reducing the risk of unauthorized access and lateral movement within the network.",
    "m1049": "Choose this option if the component uses Antivirus/Antimalware. Antivirus/Antimalware solutions utilize signatures, heuristics, and behavioral analysis to detect, block, and remediate malicious software, including viruses, trojans, ransomware, and spyware. These solutions continuously monitor endpoints and systems for known malicious patterns and suspicious behaviors that indicate compromise. Antivirus/Antimalware software should be deployed across all devices, with automated updates to ensure protection against the latest threats.",
    "m1013": "Choose this option if the component uses Application Developer Guidance. Application Developer Guidance focuses on providing developers with the knowledge, tools, and best practices needed to write secure code, reduce vulnerabilities, and implement secure design principles. By integrating security throughout the software development lifecycle (SDLC), this mitigation aims to prevent the introduction of exploitable weaknesses in applications, systems, and APIs.",
    "m1048": "Choose this option if the component uses Application Isolation and Sandboxing. Application Isolation and Sandboxing refers to the technique of restricting the execution of code to a controlled and isolated environment (e.g., a virtual environment, container, or sandbox). This method prevents potentially malicious code from affecting the rest of the system or network by limiting access to sensitive resources and critical operations. The goal is to contain threats and minimize their impact.",
    "m1047": "Choose this option if the component uses Audit. Auditing is the process of recording activity and systematically reviewing and analyzing the activity and system configurations. The primary purpose of auditing is to detect anomalies and identify potential threats or weaknesses in the environment. Proper auditing configurations can also help to meet compliance requirements. The process of auditing encompasses regular analysis of user behaviors and system logs in support of proactive security measures.",
    "m1040": "Choose this option if the component uses Behavior Prevention on Endpoint. Behavior Prevention on Endpoint refers to the use of technologies and strategies to detect and block potentially malicious activities by analyzing the behavior of processes, files, API calls, and other endpoint events. Rather than relying solely on known signatures, this approach leverages heuristics, machine learning, and real-time monitoring to identify anomalous patterns indicative of an attack.",
    "m1046": "Choose this option if the component uses Boot Integrity. Boot Integrity ensures that a system starts securely by verifying the integrity of its boot process, operating system, and associated components. This mitigation focuses on leveraging secure boot mechanisms, hardware-rooted trust, and runtime integrity checks to prevent tampering during the boot sequence. It is designed to thwart adversaries attempting to modify system firmware, bootloaders, or critical OS components.",
    "m1045": "Choose this option if the component uses Code Signing. Code Signing is a security process that ensures the authenticity and integrity of software by digitally signing executables, scripts, and other code artifacts. It prevents untrusted or malicious code from executing by verifying the digital signatures against trusted sources. Code signing protects against tampering, impersonation, and distribution of unauthorized or malicious software, forming a critical defense against supply chain and software exploitation attacks.",
    "m1043": "Choose this option if the component uses Credential Access Protection. Credential Access Protection focuses on implementing measures to prevent adversaries from obtaining credentials, such as passwords, hashes, tokens, or keys, that could be used for unauthorized access. This involves restricting access to credential storage mechanisms, hardening configurations to block credential dumping methods, and using monitoring tools to detect suspicious credential-related activity.",
    "m1053": "Choose this option if the component uses Data Backup. Data Backup involves taking and securely storing backups of data from end-user systems and critical servers. It ensures that data remains available in the event of system compromise, ransomware attacks, or other disruptions. Backup processes should include hardening backup systems, implementing secure storage solutions, and keeping backups isolated from the corporate network to prevent compromise during active incidents.",
    "m1057": "Choose this option if the component uses Data Loss Prevention. Data Loss Prevention (DLP) involves implementing strategies and technologies to identify, categorize, monitor, and control the movement of sensitive data within an organization. This includes protecting data formats indicative of Personally Identifiable Information (PII), intellectual property, or financial data from unauthorized access, transmission, or exfiltration. DLP solutions integrate with network, endpoint, and cloud platforms to enforce security policies and prevent accidental or malicious data leaks.",
    "m1042": "Choose this option if the component uses Disable or Remove Feature or Program. Disable or remove unnecessary and potentially vulnerable software, features, or services to reduce the attack surface and prevent abuse by adversaries. This involves identifying software or features that are no longer needed or that could be exploited and ensuring they are either removed or properly disabled.",
    "m1055": "Choose this option if the component uses Do Not Mitigate. The Do Not Mitigate category highlights scenarios where attempting to mitigate a specific technique may inadvertently increase the organization's security risk or operational instability. This could happen due to the complexity of the system, the integration of critical processes, or the potential for introducing new vulnerabilities. Instead of direct mitigation, these situations may call for alternative strategies such as detection, monitoring, or response. The Do Not Mitigate category underscores the importance of assessing the trade-offs between mitigation efforts and overall system integrity.",
    "m1041": "Choose this option if the component uses Encrypt Sensitive Information. Protect sensitive information at rest, in transit, and during processing by using strong encryption algorithms. Encryption ensures the confidentiality and integrity of data, preventing unauthorized access or tampering.",
    "m1039": "Choose this option if the component uses Environment Variable Permissions. Restrict the modification of environment variables to authorized users and processes by enforcing strict permissions and policies. This ensures the integrity of environment variables, preventing adversaries from abusing or altering them for malicious purposes.",
    "m1038": "Choose this option if the component uses Execution Prevention. Prevent the execution of unauthorized or malicious code on systems by implementing application control, script blocking, and other execution prevention mechanisms. This ensures that only trusted and authorized code is executed, reducing the risk of malware and unauthorized actions.",
    "m1050": "Choose this option if the component uses Exploit Protection. Deploy capabilities that detect, block, and mitigate conditions indicative of software exploits. These capabilities aim to prevent exploitation by addressing vulnerabilities, monitoring anomalous behaviors, and applying exploit-mitigation techniques to harden systems and software.",
    "m1037": "Choose this option if the component uses Filter Network Traffic. 	Employ network appliances and endpoint software to filter ingress, egress, and lateral network traffic. This includes protocol-based filtering, enforcing firewall rules, and blocking or restricting traffic based on predefined conditions to limit adversary movement and data exfiltration.",
    "m1035": "Choose this option if the component uses Limit Access to Resource Over Network. Restrict access to network resources, such as file shares, remote systems, and services, to only those users, accounts, or systems with a legitimate business requirement. This can include employing technologies like network concentrators, RDP gateways, and zero-trust network access (ZTNA) models, alongside hardening services and protocols.",
    "m1034": "Choose this option if the component uses Limit Hardware Installation. Prevent unauthorized users or groups from installing or using hardware, such as external drives, peripheral devices, or unapproved internal hardware components, by enforcing hardware usage policies and technical controls. This includes disabling USB ports, restricting driver installation, and implementing endpoint security tools to monitor and block unapproved devices.",
    "m1033": "Choose this option if the component uses Limit Software Installation. Prevent users or groups from installing unauthorized or unapproved software to reduce the risk of introducing malicious or vulnerable applications. This can be achieved through allowlists, software restriction policies, endpoint management tools, and least privilege access principles.",
    "m1032": "Choose this option if the component uses Multi-factor Authentication. Multi-Factor Authentication (MFA) enhances security by requiring users to provide at least two forms of verification to prove their identity before granting access.",
    "m1031": "Choose this option if the component uses Network Intrusion Prevention. Multi-Factor Authentication (MFA) enhances security by requiring users to provide at least two forms of verification to prove their identity before granting access.",
    "m1030": "Choose this option if the component uses Network Segmentation. Network segmentation involves dividing a network into smaller, isolated segments to control and limit the flow of traffic between devices, systems, and applications. By segmenting networks, organizations can reduce the attack surface, restrict lateral movement by adversaries, and protect critical assets from compromise.",
    "m1028": "Choose this option if the component uses Operating System Configuration. Operating System Configuration involves adjusting system settings and hardening the default configurations of an operating system (OS) to mitigate adversary exploitation and prevent abuse of system functionality. Proper OS configurations address security vulnerabilities, limit attack surfaces, and ensure robust defense against a wide range of techniques.",
    "m1060": "Choose this option if the component uses Out-of-Band Communications Channel. Establish secure out-of-band communication channels to ensure the continuity of critical communications during security incidents, data integrity attacks, or in-network communication failures. Out-of-band communication refers to using an alternative, separate communication path that is not dependent on the potentially compromised primary network infrastructure. This method can include secure messaging apps, encrypted phone lines, satellite communications, or dedicated emergency communication systems. Leveraging these alternative channels reduces the risk of adversaries intercepting, disrupting, or tampering with sensitive communications and helps coordinate an effective incident response.",
    "m1027": "Choose this option if the component uses Password Policies. Set and enforce secure password policies for accounts to reduce the likelihood of unauthorized access. Strong password policies include enforcing password complexity, requiring regular password changes, and preventing password reuse.",
    "m1056": "Choose this option if the component uses Pre-compromise measures. Pre-compromise mitigations involve proactive measures and defenses implemented to prevent adversaries from successfully identifying and exploiting weaknesses during the Reconnaissance and Resource Development phases of an attack. These activities focus on reducing an organization's attack surface, identify adversarial preparation efforts, and increase the difficulty for attackers to conduct successful operations.",
    "m1026": "Choose this option if the component uses Privileged Account Management. Privileged Account Management focuses on implementing policies, controls, and tools to securely manage privileged accounts (e.g., SYSTEM, root, or administrative accounts). This includes restricting access, limiting the scope of permissions, monitoring privileged account usage, and ensuring accountability through logging and auditing.",
    "m1025": "Choose this option if the component uses Privileged Process Integrity. Privileged Process Integrity focuses on defending highly privileged processes (e.g., system services, antivirus, or authentication processes) from tampering, injection, or compromise by adversaries. These processes often interact with critical components, making them prime targets for techniques like code injection, privilege escalation, and process manipulation.",
    "m1029": "Choose this option if the component uses Remote Data Storage. Remote Data Storage focuses on moving critical data, such as security logs and sensitive files, to secure, off-host locations to minimize unauthorized access, tampering, or destruction by adversaries. By leveraging remote storage solutions, organizations enhance the protection of forensic evidence, sensitive information, and monitoring data.",
    "m1022": "Choose this option if the component uses Restrict File and Directory Permissions. Restricting file and directory permissions involves setting access controls at the file system level to limit which users, groups, or processes can read, write, or execute files. By configuring permissions appropriately, organizations can reduce the attack surface for adversaries seeking to access sensitive data, plant malicious code, or tamper with system files.",
    "m1044": "Choose this option if the component uses Restrict Library Loading. Restricting library loading involves implementing security controls to ensure that only trusted and verified libraries (DLLs, shared objects, etc.) are loaded into processes. Adversaries often abuse Dynamic-Link Library (DLL) Injection, DLL Search Order Hijacking, or LD_PRELOAD mechanisms to execute malicious code by forcing the operating system to load untrusted libraries.",
    "m1024": "Choose this option if the component uses Restrict Registry Permissions. Restricting registry permissions involves configuring access control settings for sensitive registry keys and hives to ensure that only authorized users or processes can make modifications. By limiting access, organizations can prevent unauthorized changes that adversaries might use for persistence, privilege escalation, or defense evasion.",
    "m1021": "Choose this option if the component uses Restrict Web-Based Content. Restricting web-based content involves enforcing policies and technologies that limit access to potentially malicious websites, unsafe downloads, and unauthorized browser behaviors. This can include URL filtering, download restrictions, script blocking, and extension control to protect against exploitation, phishing, and malware delivery.",
    "m1054": "Choose this option if the component uses Software Configuration. Software configuration refers to making security-focused adjustments to the settings of applications, middleware, databases, or other software to mitigate potential threats. These changes help reduce the attack surface, enforce best practices, and protect sensitive data.",
    "m1020": "Choose this option if the component uses SSL/TLS Inspection. 	SSL/TLS inspection involves decrypting encrypted network traffic to examine its content for signs of malicious activity. This capability is crucial for detecting threats that use encryption to evade detection, such as phishing, malware, or data exfiltration. After inspection, the traffic is re-encrypted and forwarded to its destination.",
    "m1019": "Choose this option if the component uses Threat Intelligence Program. A Threat Intelligence Program enables organizations to proactively identify, analyze, and act on cyber threats by leveraging internal and external data sources. The program supports decision-making processes, prioritizes defenses, and improves incident response by delivering actionable intelligence tailored to the organization's risk profile and operational environment.",
    "m1051": "Choose this option if the component uses Update Software. Software updates ensure systems are protected against known vulnerabilities by applying patches and upgrades provided by vendors. Regular updates reduce the attack surface and prevent adversaries from exploiting known security gaps. This includes patching operating systems, applications, drivers, and firmware.",
    "m1052": "Choose this option if the component uses User Account Control. User Account Control (UAC) is a security feature in Microsoft Windows that prevents unauthorized changes to the operating system. UAC prompts users to confirm or provide administrator credentials when an action requires elevated privileges. Proper configuration of UAC reduces the risk of privilege escalation attacks.",
    "m1018": "Choose this option if the component uses User Account Management. User Account Management involves implementing and enforcing policies for the lifecycle of user accounts, including creation, modification, and deactivation. Proper account management reduces the attack surface by limiting unauthorized access, managing account privileges, and ensuring accounts are used according to organizational policies.",
    "m1017": "Choose this option if the component uses User Training. User Training involves educating employees and contractors on recognizing, reporting, and preventing cyber threats that rely on human interaction, such as phishing, social engineering, and other manipulative techniques. Comprehensive training programs create a human firewall by empowering users to be an active component of the organization's cybersecurity defenses.",
    "m1016": "Choose this option if the component uses Vulnerability Scanning. Vulnerability scanning involves the automated or manual assessment of systems, applications, and networks to identify misconfigurations, unpatched software, or other security weaknesses. The process helps prioritize remediation efforts by classifying vulnerabilities based on risk and impact, reducing the likelihood of exploitation by adversaries.",
    "m1058": "Choose this option if the component uses Antivirus/Antimalware. Mobile security products, such as Mobile Threat Defense (MTD), offer various device-based mitigations against certain behaviors.",
    "m1013": "Choose this option if the component uses Application Developer Guidance. Application Developer Guidance focuses on providing developers with the knowledge, tools, and best practices needed to write secure code, reduce vulnerabilities, and implement secure design principles. By integrating security throughout the software development lifecycle (SDLC), this mitigation aims to prevent the introduction of exploitable weaknesses in applications, systems, and APIs.",
    "m1002": "Choose this option if the component uses Attestation. Enable remote attestation capabilities when available (such as Android SafetyNet or Samsung Knox TIMA Attestation) and prohibit devices that fail the attestation from accessing enterprise resources.",
    "m1010": "Choose this option if the component uses Deploy Compromised Device Detection Method. A variety of methods exist that can be used to enable enterprises to identify compromised (e.g. rooted/jailbroken) devices, whether using security mechanisms built directly into the device, third-party mobile security applications, enterprise mobility management (EMM)/mobile device management (MDM) capabilities, or other methods. Some methods may be trivial to evade while others may be more sophisticated.",
    "m1059": "Choose this option if the component is marked as Do Not Mitigate. This category is to associate techniques that mitigation might increase risk of compromise and therefore mitigation is not recommended.",
    "m1009": "Choose this option if the component uses Encrypt Network Traffic. Application developers should encrypt all of their application network traffic using the Transport Layer Security (TLS) protocol to ensure protection of sensitive data and deter network-based attacks. If desired, application developers could perform message-based encryption of data before passing it for TLS encryption.",
    "m1012": "Choose this option if the component uses Enterprise Policy. An enterprise mobility management (EMM), also known as mobile device management (MDM), system can be used to provision policies to mobile devices to control aspects of their allowed behavior.",
    "m1014": "Choose this option if the component uses Interconnection Filtering. In order to mitigate Signaling System 7 (SS7) exploitation, the Communications, Security, Reliability, and Interoperability Council (CSRIC) describes filtering interconnections between network operators to block inappropriate requests.",
    "m1003": "Choose this option if the component uses Lock Bootloader. On devices that provide the capability to unlock the bootloader (hence allowing any operating system code to be flashed onto the device), perform periodic checks to ensure that the bootloader is locked.",
    "m1001": "Choose this option if the component uses Security Updates. Install security updates in response to discovered vulnerabilities.",
    "m1004": "Choose this option if the component uses System Partition Integrity. Ensure that Android devices being used include and enable the Verified Boot capability, which cryptographically ensures the integrity of the system partition.",
    "m1006": "Choose this option if the component uses Use Recent OS Version. New mobile operating system versions bring not only patches against discovered vulnerabilities but also often bring security architecture improvements that provide resilience against potential vulnerabilities or weaknesses that have not yet been discovered. They may also bring improvements that block use of observed adversary techniques.",
    "m1011": "Choose this option if the component uses User Guidance. New mobile operating system versions bring not only patches against discovered vulnerabilities but also often bring security architecture improvements that provide resilience against potential vulnerabilities or weaknesses that have not yet been discovered. They may also bring improvements that block use of observed adversary techniques."
},
    {
       "m0801": "Choose this option if the component uses Access Management. Access Management technologies can be used to enforce authorization polices and decisions, especially when existing field devices do not provide sufficient capabilities to support user identification and authentication. These technologies typically utilize an in-line network device or gateway system to prevent access to unauthenticated users, while also integrating with an authentication service to first verify user credentials.",
    "m0936": "Choose this option if the component uses Account Use Policies. Configure features related to account use like login attempt lockouts, specific login times, etc.",
    "m0915": "Choose this option if the component uses Active Directory Configuration. Configure features related to account use like login attempt lockouts, specific login times, etc.",
    "m0949": "Choose this option if the component uses Antivirus/Antimalware. Use signatures or heuristics to detect malicious software. Within industrial control environments, antivirus/antimalware installations should be limited to assets that are not involved in critical or real-time operations. To minimize the impact to system availability, all products should first be validated within a representative test environment before deployment to production systems.",
    "m0913": "Choose this option if the component uses Application Developer Guidance. This mitigation describes any guidance or training given to developers of applications to avoid introducing security weaknesses that an adversary may be able to take advantage of.",
    "m0948": "Choose this option if the component uses Application Isolation and Sandboxing. Restrict the execution of code to a virtual environment on or in-transit to an endpoint system.",
    "m0947": "Choose this option if the component uses Audit. Perform audits or scans of systems, permissions, insecure software, insecure configurations, etc. to identify potential weaknesses. Perform periodic integrity checks of the device to validate the correctness of the firmware, software, programs, and configurations. Integrity checks, which typically include cryptographic hashes or digital signatures, should be compared to those obtained at known valid states, especially after events like device reboots, program downloads, or program restarts.",
    "m0800": "Choose this option if the component uses Authorization Enforcement. The device or system should restrict read, manipulate, or execute privileges to only authenticated users who require access based on approved security policies. Role-based Access Control (RBAC) schemes can help reduce the overhead of assigning permissions to the large number of devices within an ICS. For example, IEC 62351 provides examples of roles used to support common system operations within the electric power sector , while IEEE 1686 defines standard permissions for users of IEDs.",
    "m0946": "Choose this option if the component uses Boot Integrity. Use secure methods to boot a system and verify the integrity of the operating system and loading mechanisms.",
    "m0945": "Choose this option if the component uses Code Signing. Enforce binary and application integrity with digital signature verification to prevent untrusted code from executing.",
    "m0802": "Choose this option if the component uses Communication Authenticity. When communicating over an untrusted network, utilize secure network protocols that both authenticate the message sender and can verify its integrity. This can be done either through message authentication codes (MACs) or digital signatures, to detect spoofed network messages and unauthorized connections.",
    "m0953": "Choose this option if the component uses Data Backup. Take and store data backups from end user systems and critical servers. Ensure backup and storage systems are hardened and kept separate from the corporate network to prevent compromise. Maintain and exercise incident response plans , including the management of 'gold-copy' back-up images and configurations for key systems to enable quick recovery and response from adversarial activities that impact control, view, or availability.",
    "m0803": "Choose this option if the component uses Data Loss Prevention. Data Loss Prevention (DLP) technologies can be used to help identify adversarial attempts to exfiltrate operational information, such as engineering plans, trade secrets, recipes, intellectual property, or process telemetry. DLP functionality may be built into other security products such as firewalls or standalone suites running on the network and host-based agents. DLP may be configured to prevent the transfer of information through corporate resources such as email, web, and physical media such as USB for host-based solutions.",
    "m0942": "Choose this option if the component uses Disable or Remove Feature or Program. Remove or deny access to unnecessary and potentially vulnerable software to prevent abuse by adversaries.",
    "m0808": "Choose this option if the component uses Encrypt Network Traffic. Utilize strong cryptographic techniques and protocols to prevent eavesdropping on network communications.",
    "m0941": "Choose this option if the component uses Encrypt Sensitive Information. Protect sensitive data-at-rest with strong encryption.",
    "m0938": "Choose this option if the component uses Execution Prevention. Protect sensitive data-at-rest with strong encryption.",
    "m0950": "Choose this option if the component uses Exploit Protection. Use capabilities to detect and block conditions that may lead to or be indicative of a software exploit occurring.",
    "m0937": "Choose this option if the component uses Filter Network Traffic. Use network appliances to filter ingress or egress traffic and perform protocol-based filtering. Configure software on endpoints to filter network traffic. Perform inline allow/denylisting of network messages based on the application layer (OSI Layer 7) protocol, especially for automation protocols. Application allowlists are beneficial when there are well-defined communication sequences, types, rates, or patterns needed during expected system operations. Application denylists may be needed if all acceptable communication sequences cannot be defined, but instead a set of known malicious uses can be denied (e.g., excessive communication attempts, shutdown messages, invalid commands). Devices performing these functions are often referred to as deep-packet inspection (DPI) firewalls, context-aware firewalls, or firewalls blocking specific automation/SCADA protocol aware firewalls.",
    "m0804": "Choose this option if the component uses Human User Authentication. Require user authentication before allowing access to data or accepting commands to a device. While strong multi-factor authentication is preferable, it is not always feasible within ICS environments. Performing strong user authentication also requires additional security controls and processes which are often the target of related adversarial techniques (e.g., Valid Accounts, Default Credentials). Therefore, associated ATT&CK mitigations should be considered in addition to this, including Multi-factor Authentication, Account Use Policies, Password Policies, User Account Management, Privileged Account Management, and User Account Control.",
    "m0935": "Choose this option if the component uses Limit Access to Resource Over Network. Prevent access to file shares, remote access to systems, unnecessary services. Mechanisms to limit access may include use of network concentrators, RDP gateways, etc.",
    "m0934": "Choose this option if the component uses Limit Hardware Installation. Block users or groups from installing or using unapproved hardware on systems, including USB devices.",
    "m0805": "Choose this option if the component uses Mechanical Protection Layers. Utilize a layered protection design based on physical or mechanical protection systems to prevent damage to property, equipment, human safety, or the environment. Examples include interlocks, rupture disk, release values, etc.",
    "m0806": "Choose this option if the component uses Minimize Wireless Signal Propagation. Wireless signals frequently propagate outside of organizational boundaries, which provide opportunities for adversaries to monitor or gain unauthorized access to the wireless network. To minimize this threat, organizations should implement measures to detect, understand, and reduce unnecessary RF propagation.",
    "m0816": "Choose this option if the component is marked as Mitigation Limited or Not Effective, indicating that standard preventative controls may not adequately mitigate the attack technique.",
    "m0932": "Choose this option if the component uses Multi-factor Authentication. Use two or more pieces of evidence to authenticate to a system; such as username and password in addition to a token from a physical smart card or token generator. Within industrial control environments assets such as low-level controllers, workstations, and HMIs have real-time operational control and safety requirements which may restrict the use of multi-factor.",
    "m0807": "Choose this option if the component uses Network Allowlists. Network allowlists can be implemented through either host-based files or system hosts files to specify what connections (e.g., IP address, MAC address, port, protocol) can be made from a device. Allowlist techniques that operate at the application layer (e.g., DNP3, Modbus, HTTP) are addressed in Filter Network Traffic mitigation.",
    "m0931": "Choose this option if the component uses Network Intrusion Prevention. Use intrusion detection signatures to block traffic at network boundaries. In industrial control environments, network intrusion prevention should be configured so it will not disrupt protocols and communications responsible for real-time functions related to control or safety.",
    "m0930": "Choose this option if the component uses Network Segmentation. Architect sections of the network to isolate critical systems, functions, or resources. Use physical and logical segmentation to prevent access to potentially sensitive systems and information. Use a DMZ to contain any internet-facing services that should not be exposed from the internal network. Restrict network access to only required systems and services. In addition, prevent systems from other networks or business functions (e.g., enterprise) from accessing critical process control systems. For example, in IEC 62443, systems within the same secure level should be grouped into a zone, and access to that zone is restricted by a conduit, or mechanism to restrict data flows between zones by segmenting the network.",
    "m0928": "Choose this option if the component uses Operating System Configuration. Make configuration changes related to the operating system or a common feature of the operating system that result in system hardening against techniques.",
    "m0809": "Choose this option if the component uses Operational Information Confidentiality. Deploy mechanisms to protect the confidentiality of information related to operational processes, facility locations, device configurations, programs, or databases that may have information that can be used to infer organizational trade-secrets, recipes, and other intellectual property (IP).",
    "m0810": "Choose this option if the component uses an Out-of-Band Communications Channel. Have alternative methods to support communication requirements during communication failures and data integrity attacks.",
    "m0927": "Choose this option if the component uses Password Policies. Set and enforce secure password policies for accounts.",
    "m0926": "Choose this option if the component uses Privileged Account Management. Manage the creation, modification, use, and permissions associated to privileged accounts, including SYSTEM and root.",
    "m0811": "Choose this option if the component uses Redundancy of Service. Redundancy could be provided for both critical ICS devices and services, such as back-up devices or hot-standbys.",
    "m0922": "Choose this option if the component uses Restrict File and Directory Permissions. Restrict access by setting directory and file permissions that are not specific to users or privileged accounts.",
    "m0944": "Choose this option if the component uses Restrict Library Loading. Prevent abuse of library loading mechanisms in the operating system and software to load untrusted code by configuring appropriate library loading mechanisms and investigating potential vulnerable software.",
    "m0924": "Choose this option if the component uses Restrict Registry Permissions. Restrict the ability to modify certain hives or keys in the Windows Registry.",
    "m0921": "Choose this option if the component uses Restrict Web-Based Content. Restrict use of certain websites, block downloads/attachments, block Javascript, restrict browser extensions, etc.",
    "m0812": "Choose this option if the component uses Safety Instrumented Systems. Systems Utilize Safety Instrumented Systems (SIS) to provide an additional layer of protection to hazard scenarios that may cause property damage. A SIS will typically include sensors, logic solvers, and a final control element that can be used to automatically respond to an hazardous condition . Ensure that all SISs are segmented from operational networks to prevent them from being targeted by additional adversarial behavior.",
    "m0954": "Choose this option if the component uses Software Configuration. Implement configuration changes to software (other than the operating system) to mitigate security risks associated with how the software operates.",
    "m0813": "Choose this option if the component uses Software Process and Device Authentication. Require the authentication of devices and software processes where appropriate. Devices that connect remotely to other systems should require strong authentication to prevent spoofing of communications. Furthermore, software processes should also require authentication when accessing APIs.",
    "m0920": "Choose this option if the component uses SSL/TLS Inspection. Break and inspect SSL/TLS sessions to look at encrypted web traffic for adversary activity.",
    "m0814": "Choose this option if the component uses Static Network Configuration. Configure hosts and devices to use static network configurations when possible, protocols that require dynamic discovery/addressing (e.g., ARP, DHCP, DNS) can be used to manipulate network message forwarding and enable various AiTM attacks. This mitigation may not always be usable due to limited device features or challenges introduced with different network configurations.",
    "m0817": "Choose this option if the component uses Supply Chain Management. Implement a supply chain management program, including policies and procedures to ensure all devices and components originate from a trusted supplier and are tested to verify their integrity.",
    "m0919": "Choose this option if the component uses a Threat Intelligence Program. A threat intelligence program helps an organization generate their own threat intelligence information and track trends to inform defensive priorities to mitigate risk.",
    "m0951": "Choose this option if the component uses Update Software. Perform regular software updates to mitigate exploitation risk. Software updates may need to be scheduled around operational down times.",
    "m0918": "Choose this option if the component uses User Account Management. Manage the creation, modification, use, and permissions associated to user accounts.",
    "m0917": "Choose this option if the component uses User Training. Train users to be aware of access or manipulation attempts by an adversary to reduce the risk of successful spearphishing, social engineering, and other techniques that involve user interaction.",
    "m0818": "Choose this option if the component uses Validate Program Inputs. Devices and programs designed to interact with control system parameters should validate the format and content of all user inputs and actions to ensure the values are within intended operational ranges. These values should be evaluated and further enforced through the program logic running on the field controller. If a problematic or invalid input is identified, the programs should either utilize a predetermined safe value or enter a known safe state, while also logging or alerting on the event.",
    "m0916": "Choose this option if the component uses Vulnerability Scanning. Vulnerability scanning is used to find potentially exploitable software vulnerabilities to remediate them.",
    "m0815": "Choose this option if the component uses Watchdog Timers. Utilize watchdog timers to ensure devices can quickly detect whether a system is unresponsive."
    },
    {
    "amlm0000": "Choose this option if the component limits the public release of technical and organizational information to mitigate the risk of adversaries learning about its machine learning stack.",
    "amlm0001": "Choose this option if the component limits the public release of model artifacts such as data, algorithms, and model checkpoints to protect sensitive project details.",
    "amlm0002": "Choose this option if the component employs passive ML output obfuscation to reduce the fidelity of model outputs and hinder adversarial extraction of information.",
    "amlm0003": "Choose this option if the component incorporates model hardening techniques (e.g., adversarial training) to improve robustness against adversarial inputs.",
    "amlm0004": "Choose this option if the component restricts the total number and rate of ML model queries to prevent abuse.",
    "amlm0005": "Choose this option if the component controls access to ML models and data at rest through robust internal access controls.",
    "amlm0006": "Choose this option if the component uses ensemble methods for inference to improve resilience against adversarial attacks.",
    "amlm0007": "Choose this option if the component sanitizes training data by detecting and removing poisoned or unwanted content before and during model training.",
    "amlm0008": "Choose this option if the component validates its machine learning models—checking for backdoors, adversarial bias, and data drift—to ensure proper performance.",
    "amlm0009": "Choose this option if the component utilizes multi-modal sensors to integrate diverse data inputs and avoid a single point of failure in physical security.",
    "amlm0010": "Choose this option if the component applies input restoration techniques to preprocess inference data and mitigate adversarial perturbations.",
    "amlm0011": "Choose this option if the component restricts library loading to prevent the execution of untrusted code by enforcing secure loading mechanisms.",
    "amlm0012": "Choose this option if the component encrypts sensitive information, including ML models and related data, to safeguard against unauthorized access.",
    "amlm0013": "Choose this option if the component enforces code signing to maintain binary and application integrity, preventing the execution of untrusted code.",
    "amlm0014": "Choose this option if the component verifies ML artifacts using cryptographic checksums to detect any unauthorized modifications.",
    "amlm0015": "Choose this option if the component integrates adversarial input detection mechanisms to identify and block atypical or potentially malicious queries.",
    "amlm0016": "Choose this option if the component performs vulnerability scanning on model artifacts and downstream products to identify and remediate exploitable vulnerabilities.",
    "amlm0017": "Choose this option if the component employs model distribution methods, such as cloud deployment or centralized feature computation, to reduce the attack surface from edge devices.",
    "amlm0018": "Choose this option if the component includes user training for ML developers on secure coding practices and the identification of ML vulnerabilities.",
    "amlm0019": "Choose this option if the component controls access to production ML models by enforcing user verification, API authentication, and query monitoring.",
    "amlm0020": "Choose this option if the component implements generative AI guardrails—such as filters or rule-based validators—to prevent undesired inputs and outputs.",
    "amlm0021": "Choose this option if the component applies generative AI guidelines in system prompts to direct model outputs and enforce safety and security parameters.",
    "amlm0022": "Choose this option if the component uses generative AI model alignment techniques, including fine-tuning methods, to improve safety and adherence to content policies.",
    "amlm0023": "Choose this option if the component includes an AI Bill of Materials that documents all artifacts and resources used in building the AI, reducing supply chain risks.",
    "amlm0024": "Choose this option if the component implements AI telemetry logging to monitor inputs and outputs and support threat detection.",
    "amlm0025": "Choose this option if the component maintains AI dataset provenance by recording a detailed history of dataset sources and modifications."
    },
    {
    "mid001": "Choose this option if the component uses Software Only Bootloader Authentication. Bootloader hashes or signatures are verified purely by software running on the main CPU, with keys and verification logic kept in memory/flash, forming a software-based chain of trust.",
    "mid002": "Choose this option if the component uses Hardware-backed Bootloader Authentication. A hardware root of trust (e.g., ROM, TPM, secure element) measures and verifies each bootloader stage before execution, anchoring secure boot in immutable hardware.",
    "mid003": "Choose this option if the component performs Periodic/Continuous Integrity Measurement and Remote Attestation. The device regularly re-hashes firmware, OS, memory, timing, etc., and sends attestation reports to a remote verifier to prove ongoing integrity.",
    "mid004": "Choose this option if the component implements Memory Hardening Against Code Injection. Look for NX/DEP or W^X policies, ASLR (including KASLR), stack canaries, safe/unsafe stacks, or other measures that restrict executable memory and randomize addresses.",
    "mid005": "Choose this option if the component is written in Memory Safe Programming Languages. Critical drivers, kernel parts, or apps are implemented in Rust, Java, Go, Python, C#, or similar languages that enforce bounds checking and prevent common memory errors.",
    "mid006": "Choose this option if the component employs Driver Memory Isolation. Drivers run in separate address spaces or user space (microkernel, IOMMU, user-mode drivers), limiting their ability to access kernel or other driver memory.",
    "mid007": "Choose this option if the component includes Control Flow Manipulation Protections. Evidence includes Control Flow Integrity (CFI), shadow call stacks, pointer authentication (PAC), branch target identification (BTI), or compiler flags that enforce valid control-flow targets.",
    "mid008": "Choose this option if the component uses Decidable Protocols and Parsers. Protocols are designed with regular or deterministic context-free grammars and parsed by finite-state or push-down automata, following LangSec principles to ensure decidable parsing.",
    "mid009": "Choose this option if the component performs Runtime System Integrity Checking. The OS or security tools verify hashes/signatures of files or blocks as they are read (e.g., dm-verity, IMA), blocking or alerting on integrity failures.",
    "mid010": "Choose this option if the component disables Runtime OS Driver Loading. Kernel modules cannot be added after boot; module loading is locked down or entirely removed, so only built-in drivers are usable.",
    "mid011": "Choose this option if the component uses OS Driver/Peripheral Authentication. Only digitally signed drivers and peripheral firmware are verified with vendor keys before they are loaded or executed.",
    "mid012": "Choose this option if the component deploys OS-based Access Control Mechanisms. The OS enforces least-privilege through MAC or capability systems (e.g., SELinux, AppArmor, seccomp) that restrict system calls and resource access.",
    "mid013": "Choose this option if the component enforces Process and Thread Memory Segmentation. MMU/MPU or virtual-memory isolation keeps each process/thread in its own address space with kernel-mediated IPC.",
    "mid014": "Choose this option if the component runs code inside Sandboxing environments. Untrusted code executes in restricted runtimes (e.g., mobile app sandbox, WASM, JavaScript engine) with filtered access to files, syscalls, and networks.",
    "mid015": "Choose this option if the component uses Containerization. Applications are wrapped in OS containers (Docker, LXC, BSD jails) with isolated filesystems, PID and network namespaces, and optionally run rootless.",
    "mid016": "Choose this option if the component implements Least Functionality. All non-essential binaries, drivers, services, and compiler/toolchain elements are removed or disabled to shrink the attack surface.",
    "mid017": "Choose this option if the component provides Security-relevant Auditing and Logging. It records user actions, config changes, updates, and service events, optionally exporting logs off-device for analysis.",
    "mid018": "Choose this option if the component requires Authentication for Privileged Functions. Administrative operations demand authenticated privileged credentials, enforce session lifetimes, and alert on failed attempts.",
    "mid019": "Choose this option if the component applies ROP Gadget Minimization. Compiler or post-compile tooling removes or neutralizes instruction sequences usable as Return-Oriented Programming gadgets.",
    "mid020": "Choose this option if the component employs Pointer Authentication. Hardware support (e.g., ARM PAC) adds and checks authentication codes on pointers to detect modification before use.",
    "mid021": "Choose this option if the component implements VM Hardening. The hypervisor's exposed devices/APIs are minimized so guest VMs see only the virtual hardware strictly required.",
    "mid022": "Choose this option if the component achieves Segmentation Through Hardware-assisted VMs. CPU virtualization extensions and a hypervisor isolate each VM's memory, I/O, and kernel.",
    "mid023": "Choose this option if the component practices Hypervisor Hardening. Hypervisor modules are privilege-reduced or sandboxed, stored immutably, and verified during secure boot.",
    "mid024": "Choose this option if the component uses Encrypted VM Isolation. Guest RAM is transparently encrypted per VM so neither the hypervisor nor other VMs can read it in plaintext.",
    "mid025": "Choose this option if the component offers End-of-Life Management Features. The vendor enables users to apply third-party firmware or keys after official support ends to maintain security.",
    "mid026": "Choose this option if the component uses Secure Firmware Update. Firmware images are signed and signature-checked, encrypted in-transit/at-rest, launched only by authenticated admins or secure channels, and protected against rollback.",
    "mid027": "Choose this option if the component relies on Validated Cryptographic Libraries. All crypto is implemented with well-maintained, independently validated (e.g., FIPS-140) libraries instead of custom or unvetted code.",
    "mid028": "Choose this option if the component employs Hardware-backed Key Storage. Secrets live inside a secure element, TPM, cryptographic coprocessor, or PUF so keys cannot be read or altered from software memory.",
    "mid029": "Choose this option if the component includes a Hardware Root of Trust. Immutable boot ROM and embedded keys verify the first bootloader stage before any other code executes.",
    "mid030": "Choose this option if the component implements Firmware Rollback Protections. After a successful update, older firmware versions are rejected via monotonically increasing version counters or similar anti-rollback checks.",
    "mid031": "Choose this option if the component uses Physical Presence Validation. Critical operations (e.g., firmware flash, mode change) require a button press, key insertion, switch flip, or comparable local action.",
    "mid032": "Choose this option if the component has a System Service Availability Manager. Hardware or software watchdogs monitor critical services and automatically restart or alert when they hang or crash.",
    "mid033": "Choose this option if the component ships with Unique and Unpredictable Factory Preinstalled Secret Keys. Each device has its own random key, preventing key reuse across units.",
    "mid034": "Choose this option if the component Authenticates Network Messages. Packets carry MACs, AEAD tags, or digital signatures that the receiver verifies before accepting or processing data.",
    "mid035": "Choose this option if the component Encrypts Network Traffic. Data in transit is protected with TLS, IPsec, AES-GCM, or equivalent encryption to maintain confidentiality and (often) integrity.",
    "mid036": "Choose this option if the component uses Cryptographic Nonces. Every message includes a unique, unpredictable value (counter, random nonce) checked to block replay attacks.",
    "mid037": "Choose this option if the component verifies Network Timestamps. Messages include time fields; the device rejects packets outside an acceptable window to detect stale or replayed data.",
    "mid038": "Choose this option if the component requires Authentication for Administrative Actions. Privileged commands demand valid credentials and are limited to authorized roles, with logs or alerts on failures.",
    "mid039": "Choose this option if the component Restricts Software Diagnostic Functions. Debug or diagnostic interfaces are removed or tightly scoped to minimal processes or hardware modes, blocking low-level access by attackers.",
    "mid040": "Choose this option if the component uses Cryptographically Signed Custom Programs. Custom/PLC programs must be signed by an org-specific private key and are rejected unless the signature verifies on-device.",
    "mid041": "Choose this option if the component uses Cryptographically Signed Vendor-supplied Programs. Only software signed by the vendor's private key is accepted, downloaded, and executed.",
    "mid042": "Choose this option if the component checks consistency between Binary/Running Code and Textual Code. The device or IDE recompiles and hashes both forms to ensure they match before use.",
    "mid043": "Choose this option if the component Manages Default Login Credentials. Factory passwords are unique, random, ≥8-char mixed case/number, and users are prompted to change them on first use.",
    "mid044": "Choose this option if the component uses Strong Cryptographic Algorithms and Protocols. It relies on well-vetted libraries and standards (e.g., TLS, WPA3) rather than home-grown crypto.",
    "mid045": "Choose this option if the component enforces Multi-factor Authentication. Users must present two or more factors (password + token/biometric) before access is granted.",
    "mid046": "Choose this option if the component implements Authentication Attempts Timeouts and Lockouts. Progressive delays or lockouts occur after repeated failed logins to thwart brute-force guessing.",
    "mid047": "Choose this option if the component provides Sufficient Entropy for Keys. It collects high-quality randomness or blocks until entropy is available so generated keys are unpredictable.",
    "mid048": "Choose this option if the component employs a Hardware Random Number Generator. A true RNG (not PRNG) uses physical noise to supply cryptographic-grade random numbers.",
    "mid049": "Choose this option if the component uses Secure Password Storage. Passwords are stored only as salted, cryptographically strong hashes—never in plaintext or reversible form.",
    "mid050": "Choose this option if the component has OS Defenses Against Microarchitecture Feature Side Channels. Kernel/hypervisor applies Spectre/Meltdown mitigations (retpolines, cache flush, page-table isolation).",
    "mid051": "Choose this option if the component Disallows User-Provided Code. The device blocks execution of any outsider-supplied scripts/programs unless other mitigations explicitly allow them.",
    "mid052": "Choose this option if the component Physically Protects Circuit Board Traces and Chip Pins. Traces are buried or epoxied, test headers removed, and BGA or similar packages chosen to hinder probing.",
    "mid053": "Choose this option if the component uses an IOMMU to Implement DMA Access Controls. Peripheral DMA is restricted to authorized memory regions, blocking rogue devices from system RAM.",
    "mid054": "Choose this option if the component Encrypts and Authenticates Non-volatile Storage Contents. Firmware/configs are stored encrypted and integrity-checked, decrypted only inside the processor.",
    "mid055": "Choose this option if the component Uses Highly Integrated Processors to Avoid Physical Attacks. SoCs/SIPs embed CPU, RAM, flash, and buses in one package to reduce attackable off-chip wiring.",
    "mid056": "Choose this option if the component allows Administrators to Disable Removable Storage Support. USB/SD boot and filesystem mounting can be turned off (and back on) by authorized admins.",
    "mid057": "Choose this option if the component Disables Physical Development and Debugging Ports. JTAG/UART or similar debug interfaces are permanently fused off or require authenticated re-enable.",
    "mid058": "Choose this option if the component Engages Hardware Readout Protection Mechanisms. Security fuses or options lock flash readout, debug, and boot settings against unauthorized access.",
    "mid059": "Choose this option if the component follows Software Patterns for Side Channel Resistance. Code uses constant-time/data-independent operations, masking, or noise to limit timing/power leaks.",
    "mid060": "Choose this option if the component employs Dedicated Hardware Cryptographic Modules. A verified hardware engine performs crypto internally without exposing keys, offering side-channel-resistant acceleration.",
    "mid061": "Choose this option if the component uses Separate Processors for Isolation. Different CPUs handle untrusted vs. critical workloads to block Spectre/Meltdown-style cross-core side channels.",
    "mid062": "Choose this option if the component implements Hardware Mitigations for Fault Injection. On-chip sensors/TRCs, brown-out or clock tamper detectors, EMI/optical detectors, or similar circuits detect or reset on glitch attacks.",
    "mid063": "Choose this option if the component applies Software Mitigations for Fault Injection. Redundant calculations, instruction duplication, loop checks, CFI/PAC, or compiler-inserted checks detect or tolerate injected faults.",
    "mid064": "Choose this option if the component Stores Critical Code and Data in On-Chip Memory. Boot ROM, keys, or firmware reside in on-chip ROM/NVRAM/fuses protected by readout-lock (MID-058).",
    "mid065": "Choose this option if the component uses RAM Encryption. CPU enclave or per-VM memory encryption prevents cold-boot, DMA, and RowHammer data disclosure.",
    "mid066": "Choose this option if the component Implements Redundant Processing and Memory. Two-or-more CPUs/DRAM banks vote or compare results to survive faults or bit flips.",
    "mid067": "Choose this option if the component uses RowHammer-resistant DRAM/Controllers. DDR4-TRR, DDR5-PRAC, ECC with refresh/victim-row logic, or controller-based row activation counting mitigate hammering.",
    "mid068": "Choose this option if the component applies Data Bus Encryption and Message Authentication. Inter-chip links (e.g., CAN-FD, PCIe IDE) are encrypted or MAC-protected with device-unique keys.",
    "mid069": "Choose this option if the component provides Electrical Fault Protection. ESD diodes, surge suppressors, opto-isolators, or reverse-polarity guards shield external I/O lines.",
    "mid070": "Choose this option if the component enforces Peripheral Component Authentication. Devices (e.g., PCIe, TouchID sensor) cryptographically prove identity/firmware integrity before resource access.",
    "mid071": "Choose this option if the component Sanitizes and Escapes User Data for Web Apps. Output encoding, input sanitization (e.g., DOMPurify), and safe sinks block XSS.",
    "mid072": "Choose this option if the component uses Parameterized SQL Queries. DB access goes through prepared statements, stored procedures, or whitelisted inputs—never raw concatenated SQL.",
    "mid073": "Choose this option if the component has Secure HTTP Session Management. Framework-generated, unpredictable session IDs with secure cookie flags and expiry protect each login session.",
    "mid074": "Choose this option if the component includes Cross-Site Request Forgery Mitigations. CSRF tokens, double-submit cookies, SameSite, or required user interaction gate privileged HTTP actions.",
    "mid075": "Choose this option if the component implements Path Traversal Protections. Canonicalizes paths, validates filenames, confines file access to allowed directories, or uses index mapping.",
    "mid076": "Choose this option if the component performs Web Direct Object Reference Authentication. Every file or object fetch is preceded by session/permission checks via the web framework.",
    "mid077": "Choose this option if the component enforces Secure Deserialization. Data is authenticated before deserialization or uses simplified, validated formats to prevent code execution.",
    "mid078": "Choose this option if the component validates HTTP Requests/Responses. It enforces length limits and rejects CR/LF or malformed headers to prevent request smuggling/splitting.",
    "mid079": "Choose this option if the component Removes Undocumented Network Functionality. All protocol commands are documented; unused or hidden op-codes are stripped from production firmware.",
    "mid080": "Choose this option if the component imposes Network Request Processing Limits. Timeouts, connection caps, bandwidth limits, or prioritized queues resist DoS resource exhaustion.",
    "mid081": "Choose this option if the component uses Secure Network Tunnels. Legacy/insecure protocols are wrapped in TLS, IPsec, SSH, or a gateway that provides encryption and auth.",
    "mid082": "Choose this option if the component implements Post-quantum Cryptography. PQC algorithms (e.g., Kyber, Dilithium) replace RSA/ECC for key exchange or signatures.",
    "mid083": "Choose this option if the component includes a Network Firewall/ACL. Built-in rules drop or block unauthorized IPs, ports, or protocols, with logged rule changes.",
    "mid084": "Choose this option if the component Restricts Sensitive Data from Logs. Logs omit passwords, keys, PII, or full core dumps—only minimal security-relevant info is recorded.",
    "mid085": "Choose this option if the component Exports Logs Off-Device. Events are sent to a remote server in near-real-time to prevent tampering and conserve on-device storage.",
    "mid086": "Choose this option if the component enforces Hardware Authentication of Memory Access. Capability hardware (e.g., CHERI) or similar tags enforce pointer bounds and permissions.",
    "mid087": "Choose this option if the component Utilizes Formally Verified OS (Micro-)Kernels. Runs a kernel like seL4 whose core has mathematical proofs of isolation and correctness.",
    "mid088": "Choose this option if the component uses Formally Verified Parsers. Protocol/file parsers are generated or proven correct, guaranteeing memory safety and rejecting malformed input.",
    "mid089": "Choose this option if the component applies Formal Methods to Critical Functionality. Key modules are mathematically specified and proved to meet safety/security properties."
  }
    ]
